include:
  - portainer/compose.yml
  - cloudbeaver/compose.yml
  - redis-insight/compose.yml
  - mailpit/compose.yml
  # hoppscotch temporarily disabled
  #  - hoppscotch/compose.yml
  - npm/compose.yml
  - technitium/compose.yml
  - homepage/compose.yml

services:
  cert-server:
    image: busybox:latest
    container_name: cert-server
    command: httpd -f -p 80 -h /www
    volumes:
      - ./certs/public:/www
    networks:
      - dev_net
    restart: unless-stopped

  init:
    build: ./init
    volumes:
      - ./init/init.sh:/init.sh
      - ./.env:/.env
      - ./certs:/certs
    depends_on:
      # Temporary "started" condition until healthcheck is fixed
      portainer:
        condition: service_started
      cloudbeaver:
        condition: service_healthy
      # Temporary "started" condition until healthcheck is fixed
      redis-insight:
        condition: service_started
      mailpit:
        condition: service_healthy
      npm:
        condition: service_healthy
      technitium:
        condition: service_healthy
      homepage:
        condition: service_healthy
    networks:
      - dev_net

networks:
  dev_net:
    external: true
    name: ${NETWORK_NAME}
