services:
  hoppscotch:
    image: hoppscotch/hoppscotch:latest
    container_name: ${HOPPSCOTCH_CONTAINER_NAME}
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-hoppscotch}
      - WHITELISTED_ORIGINS=*
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - "${HOPPSCOTCH_PORT}:3100"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:3100" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - dev_net

  postgres:
    image: postgres:16-alpine
    container_name: ${HOPPSCOTCH_CONTAINER_NAME}_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-hoppscotch}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-hoppscotch}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev_net

networks:
  dev_net:
    external: true
    name: ${DOCKER_NETWORK_NAME}
