services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: ${MAILPIT_CONTAINER_NAME}
    volumes:
      - ./data:/data
    environment:
      - MP_DATABASE=/data/mailpit.db
    restart: unless-stopped
    ports:
      - "${MAILPIT_WEB_PORT}:8025"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8025" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - dev_net

networks:
  dev_net:
    external: true
    name: ${DOCKER_NETWORK_NAME}
