services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "${MAILPIT_SMTP_PORT:-1025}:1025"
      - "${MAILPIT_WEB_PORT:-8025}:8025"
    volumes:
      - ./data:/data
    environment:
      - MP_DATABASE=/data/mailpit.db
    restart: unless-stopped
    networks:
      - dev_net

networks:
  dev_net:
    external: true
    name: ${NETWORK_NAME:-dev-net}
