services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: ${CLOUDBEAVER_CONTAINER_NAME}
    ports:
      - "${CLOUDBEAVER_PORT}:8978"
    volumes:
      - ./data:/opt/cloudbeaver/workspace
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8978/" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - dev_net

networks:
  dev_net:
    external: true
    name: ${NETWORK_NAME}
