services:
  nats-nui:
    image: nats-nui/nui:latest
    container_name: ${NATS_NUI_CONTAINER_NAME:-nats-nui}
    ports:
      - "${NATS_NUI_PORT:-31311}:31311"
    volumes:
      - ./db:/db
    restart: unless-stopped
    networks:
      - dev_net

networks:
  dev_net:
    external: true
    name: ${DOCKER_NETWORK_NAME}
