services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: ${PORTAINER_CONTAINER_NAME}
    ports:
      - "${PORTAINER_WEB_PORT_HTTP}:9000"
      - "${PORTAINER_WEB_PORT_HTTPS}:9443"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    restart: unless-stopped
    # Healthcheck temporarily disabled
    #    healthcheck:
    #      test: [ "CMD-SHELL", "wget -q -O /dev/null http://localhost:9000 || exit 1" ]
    #      interval: 30s
    #      timeout: 10s
    #      retries: 3
    networks:
      - dev_net

networks:
  dev_net:
    external: true
    name: ${NETWORK_NAME}
