services:
  redis-insight:
    image: redis/redisinsight:latest
    container_name: ${REDIS_INSIGHT_CONTAINER_NAME}
    ports:
      - "${REDIS_INSIGHT_PORT}:5540"
    restart: unless-stopped
    # Healthcheck temporarily disabled
    #    healthcheck:
    #      test: [ "CMD-SHELL", "wget -q -O /dev/null http://localhost:5540/api/health || exit 1" ]
    #      interval: 30s
    #      timeout: 10s
    #      retries: 3
    volumes:
      - ./data:/data
    networks:
      - dev_net

networks:
  dev_net:
    external: true
    name: ${DOCKER_NETWORK_NAME}
