services:
  npm:
    # Using specific version instead of latest
    # to avoid possible SSL cert upload issue
    image: jc21/nginx-proxy-manager:2.10.4
    container_name: ${NPM_CONTAINER_NAME}
    ports:
      - "80:80"
      - "443:443"
      - "${NPM_WEB_PORT}:81"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    networks:
      - dev_net
#    healthcheck:
#      test: [ "CMD", "/usr/bin/check-health" ]
#      interval: 10s
#      timeout: 3s

networks:
  dev_net:
    external: true
    name: ${NETWORK_NAME:-dev-net}
